[package]
name = "k_means"
version.workspace = true
edition.workspace = true

[dependencies]
num-traits.workspace = true
rand.workspace = true

base = { path = "../base" }
common = { path = "../common" }
stoppable_rayon = { path = "../stoppable_rayon" }

[lints]
workspace = true
