[default.extend-words]
ND = "ND"
DUR = "DUR"
ANS = "ANS"
RABIT = "RABIT"

[default]
extend-ignore-re = [
    # Latex formula
    "\\$.+?\\$",
]

[files]
extend-exclude = ["vendor/pg_config/*.txt", "vendor/pgrx_binding/*.rs"]
