[package]
name = "storage"
version.workspace = true
edition.workspace = true

[features]
stand-alone-test = []

[dependencies]
base = { path = "../base" }
common = { path = "../common" }

[lints]
workspace = true
