[package]
name = "storage"
version.workspace = true
edition.workspace = true

[dependencies]
base = { path = "../base" }
common = { path = "../common" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
