[package]
name = "interprocess_atomic_wait"
version.workspace = true
edition.workspace = true

[dependencies]
libc.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
ulock-sys = "0.1.0"

[lints]
workspace = true
