[package]
name = "detect"
version.workspace = true
edition.workspace = true

[dependencies]
rustix.workspace = true
std_detect = { git = "https://github.com/tensorchord/stdarch", rev = "e50b2f6fa7f8a9a0081c88b1793d8560462d5848" }

[lints]
workspace = true
