[build]
rustflags = ["-Ctarget-cpu=x86-64-v3"]
rustdocflags = ["--document-private-items"]

[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]
