[package]
name = "c"
version.workspace = true
edition.workspace = true

[dev-dependencies]
half.workspace = true
rand.workspace = true
detect = { path = "../detect" }

[build-dependencies]
cc = "1.0"

[lints]
workspace = true
