[package]
name = "c"
version.workspace = true
edition.workspace = true

[dev-dependencies]
half = { version = "~2.3", features = ["use-intrinsics", "rand_distr"] }
detect = { path = "../detect" }
rand = "0.8.5"

[build-dependencies]
cc = "1.0"
