[package]
name = "stand-alone-test"
version.workspace = true
edition.workspace = true

[dependencies]
base = { path = "../base" }
common = { path = "../common" }
hnsw = { path = "../hnsw" }
rayon = { path = "../rayon" }
thiserror = "1.0.58"

[lints]
workspace = true
