[package]
name = "stand_alone_test"
version.workspace = true
edition.workspace = true

[features]
stand-alone-test = []

[dependencies]
base = { path = "../base" }
common = { path = "../common" }
hnsw = { path = "../hnsw" }
rayon = { path = "../rayon" }
thiserror = "1.0.58"

[lints]
workspace = true
