name: Release for Postgres slim

on:
  workflow_dispatch:

jobs:
  pg-slim:
    strategy:
      matrix:
        version: [14, 15, 16, 17]
        platform: ["amd64"]
    runs-on: ubuntu-latest
    env:
      PG_MAJOR: ${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERIO_MODELZ_USERNAME }}
          password: ${{ secrets.DOCKERIO_MODELZ_TOKEN }}
      - name: Push binary release to Docker Registry
        uses: docker/build-push-action@v4
        with:
          context: ./docker/pg-slim
          push: true
          platforms: "linux/${{ matrix.platform }}"
          file: ./docker/pg-slim/Dockerfile
          build-args: |
            PG_MAJOR=${{ matrix.version }}
          tags: modelzai/pg-slim:${{ matrix.version }}-${{ matrix.platform }}